# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\"!\n\x03req\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x12\n\x03res\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32!\n\nCalculator\x12\x13\n\x03\x41\x64\x64\x12\x04.req\x1a\x04.res\"\x00\x62\x06proto3')
)




_REQ = _descriptor.Descriptor(
  name='req',
  full_name='req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='req.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='req.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=53,
)


_RES = _descriptor.Descriptor(
  name='res',
  full_name='res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='res.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), dict(
  DESCRIPTOR = _REQ,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:req)
  ))
_sym_db.RegisterMessage(req)

res = _reflection.GeneratedProtocolMessageType('res', (_message.Message,), dict(
  DESCRIPTOR = _RES,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:res)
  ))
_sym_db.RegisterMessage(res)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=75,
  serialized_end=108,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Calculator.Add',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
